CREATE TABLE `cash_closings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`employee_name` varchar(255) NOT NULL,
	`closing_date` date NOT NULL,
	`closing_time` timestamp NOT NULL DEFAULT (now()),
	`cash_in` decimal(10,2) NOT NULL DEFAULT '0',
	`cash` decimal(10,2) NOT NULL DEFAULT '0',
	`visa` decimal(10,2) NOT NULL DEFAULT '0',
	`total_1` decimal(10,2) NOT NULL DEFAULT '0',
	`expenses` decimal(10,2) NOT NULL DEFAULT '0',
	`system_report` decimal(10,2) NOT NULL DEFAULT '0',
	`cash_count_total` decimal(10,2) NOT NULL DEFAULT '0',
	`visa_machine_report` decimal(10,2) NOT NULL DEFAULT '0',
	`visa_wells_report` decimal(10,2) NOT NULL DEFAULT '0',
	`visa_food_on_time_report` decimal(10,2) NOT NULL DEFAULT '0',
	`total_2` decimal(10,2) NOT NULL DEFAULT '0',
	`cash_report` decimal(10,2) NOT NULL DEFAULT '0',
	`difference` decimal(10,2) NOT NULL DEFAULT '0',
	`shekel_notes_200` int DEFAULT 0,
	`shekel_notes_100` int DEFAULT 0,
	`shekel_notes_50` int DEFAULT 0,
	`shekel_notes_20` int DEFAULT 0,
	`shekel_notes_10` int DEFAULT 0,
	`shekel_notes_5` int DEFAULT 0,
	`shekel_coins_2` int DEFAULT 0,
	`shekel_coins_1` int DEFAULT 0,
	`shekel_coins_05` int DEFAULT 0,
	`dollar_amount` decimal(10,2) DEFAULT '0',
	`dinar_amount` decimal(10,2) DEFAULT '0',
	`status` enum('balanced','difference','pending') NOT NULL DEFAULT 'pending',
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cash_closings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `daily_statistics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`statistics_date` date NOT NULL,
	`total_cash_in` decimal(12,2) NOT NULL DEFAULT '0',
	`total_cash` decimal(12,2) NOT NULL DEFAULT '0',
	`total_visa` decimal(12,2) NOT NULL DEFAULT '0',
	`total_revenue` decimal(12,2) NOT NULL DEFAULT '0',
	`total_expenses` decimal(12,2) NOT NULL DEFAULT '0',
	`total_differences` decimal(12,2) NOT NULL DEFAULT '0',
	`balanced_closings` int DEFAULT 0,
	`difference_closings` int DEFAULT 0,
	`average_difference` decimal(10,2) DEFAULT '0',
	`max_difference` decimal(10,2) DEFAULT '0',
	`min_difference` decimal(10,2) DEFAULT '0',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `daily_statistics_id` PRIMARY KEY(`id`),
	CONSTRAINT `daily_statistics_statistics_date_unique` UNIQUE(`statistics_date`)
);
